export * from "./clinics";
export * from "./users";
export * from "./tutors";
export * from "./pets";
export * from "./consultations";
export * from "./anamneses";
export * from "./exams";
export * from "./vaccines";
export * from "./medical-records";
